/** @type {import("@ianvs/prettier-plugin-sort-imports").PrettierConfig} */
module.exports = {
  singleQuote: true,
  printWidth: 90,
  proseWrap: "preserve",
  endOfLine: "auto",
  tabWidth: 2,
  useTabs: false,
  trailingComma: "es5",
  requirePragma: false,
  semi: false,
  bracketSpacing: true,
  htmlWhitespaceSensitivity: "css",
  quoteProps: "as-needed",
  arrowParens: "always",
  insertPragma: false,
  bracketSameLine: false,
  vueIndentScriptAndStyle: false,
  jsxSingleQuote: true,
  jsxBracketSameLine: false,
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
  importOrder: ["<THIRD_PARTY_MODULES>", "^(?!.*[.]css$|.*[.]svg$)[./].*$", ".svg$", ".css$"],
}
